### ISSUE TITLE
Clarity on naming (B8taMenu or DirectStart)?

### ISSUE THREAD

**Issue by kawapure** [Lixkote/B8taMenu#1]
It's good to bring some clarity to user-facing naming while the project is in its infancy. Unfortunately, it's unclear on what exactly this is caused, and that could confuse users.

This repository is named B8taMenu, and this is also the name used by [the entire installer (see `source.iss`)](https://github.com/Lixkote/B8taMenu/blob/main/Installer/source.iss) and thus the installation files and default desktop shortcuts. This is the prominent name of everything.

On the other hand, the solution file is called, and references to the project in `Start menu.exe` may include, "DirectStart".

- User-facing string "Exit DirectStart" in [StartMenu.xaml:73](https://github.com/Lixkote/B8taMenu/blob/pa1/B8taMenu/StartMenu.xaml#L173)
- The folder `%USERNAME%\DirectStart`, as documented in the README, defined [here in Installer/source.iss](https://github.com/Lixkote/B8taMenu/blob/pa1/Installer/source.iss#L43) as well as the respective folders.

**Comment by Lixkote** [comment]
Sorry for that, its because the project was initailly called DirectStart. 
In the new version, i will try to change every older mention to the new name, B8taMenu.
